-- Create the telemetry table
CREATE TABLE IF NOT EXISTS install_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    total_messages_forwarded INTEGER DEFAULT 0,
    max_cluster_size INTEGER DEFAULT 0,
    city_region TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optimization: Indexes for fast filtering and pagination
CREATE INDEX IF NOT EXISTS idx_install_logs_uuid ON install_logs(uuid);
CREATE INDEX IF NOT EXISTS idx_install_logs_created_at ON install_logs(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE install_logs ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (Vercel API will use anon key)
CREATE POLICY "Allow anonymous inserts" 
ON install_logs FOR INSERT 
TO anon 
WITH CHECK (true);

-- Allow anonymous updates (Vercel API can update existing UUID stats)
CREATE POLICY "Allow anonymous updates"
ON install_logs FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

-- NO SELECT POLICY for anon (Protects data from being read publicly)
